//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSURANCE_WEP_API.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INSURANCE_DBEntities : DbContext
    {
        public INSURANCE_DBEntities()
            : base("name=INSURANCE_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_planDetails> tbl_planDetails { get; set; }
        public virtual DbSet<tbl_plans> tbl_plans { get; set; }
        public virtual DbSet<tbl_refterms> tbl_refterms { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    }
}
