//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSURANCE_WEP_API.DL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    public partial class tbl_planDetails
    {
        public long PlanDetailsId { get; set; }
        [Required]
        public long PlanId { get; set; }
        [Required]
        public long TermId { get; set; }
        [Required]
        [MaxLength(200)]
        public string TermValue { get; set; }

        //[DisplayFormat(ApplyFormatInEditMode =true, DataFormatString ="{0:yyyy-MM-dd}")]
        public System.DateTime CreatedDate { get; set; }

        //[DisplayFormat(ApplyFormatInEditMode =true, DataFormatString ="{0:yyyy-MM-dd}")]
        public System.DateTime ModifiedDate { get; set; }
        [Required]
        public long CreatedUser { get; set; }
        [Required]
        public long ModifiedUser { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_plans tbl_plans { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_refterms tbl_refterms { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_users tbl_users { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_users tbl_users1 { get; set; }
    }
}
